[workspace]

members = [
    "app",
    "context",
    "domain/entity",
    "domain/repository",
    "infra/grpc_handler",
    "infra/repository_impl",
    "proto",
    "share/error",
    "usecase",
]
