[workspace]

members = [
    "app",
    "context/app_context",
    "context/mock_context",
    "domain/entity",
    "domain/repository",
    "infra/db_schema",
    "infra/grpc_handler",
    "infra/psql_repository",
    "proto",
    "share/error",
    "usecase",
]
